name: CI Pipeline - Hari Payalagu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download repo to runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Node environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build project
      - name: Build Project
        run: npm run build

      # Step 5: Run tests if exist
      - name: Run Tests
        run: npm test --if-present
